# Generated by Django 5.0.3 on 2024-05-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='coursepssc',
            new_name='coursessc',
        ),
    ]
